<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Oryphem Library</title>
    <link rel="stylesheet" href="{{ asset('assets/templatemo-prism-flux.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>
    <!-- Loading Screen -->
    <div class="loader" id="loader">
        <div class="loader-content">
            <div class="loader-prism">
                <div class="prism-face"></div>
                <div class="prism-face"></div>
                <div class="prism-face"></div>
            </div>
            <div style="color: var(--accent-purple); font-size: 18px; text-transform: uppercase; letter-spacing: 3px;">Refracting Reality...</div>
        </div>
    </div>

    <!-- Navigation Header -->
    <header class="header" id="header">
        <nav class="nav-container">
            <a href="#home" class="logo">
                <span class="logo-text">
                    <span class="prism">Oryphem</span>
                    <span class="flux">Library</span>
                </span>
            </a>
            
            <ul class="nav-menu" id="navMenu">
                <li><a href="#home" class="nav-link active">Home</a></li>
                <li><a href="#about" class="nav-link">About</a></li>
                <li><a href="#stats" class="nav-link">Book</a></li>
                <li><a href="#contact" class="nav-link">Login</a></li>
            </ul>
            
            <div class="menu-toggle" id="menuToggle">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </nav>
    </header>

    <!-- Hero Section with 3D Carousel -->
    <section class="hero" id="home">
        <div class="carousel-container">
            <div class="carousel" id="carousel">
                <!-- Carousel items will be generated by JavaScript -->
            </div>
            
            <div class="carousel-controls">
                <button class="carousel-btn" id="prevBtn">‹</button>
                <button class="carousel-btn" id="nextBtn">›</button>
            </div>
            
            <div class="carousel-indicators" id="indicators">
                <!-- Indicators will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <!-- NEW: Prism Philosophy Section (About) -->
    <section class="philosophy-section" id="about">
        <div class="philosophy-container">
            <div class="prism-line"></div>
            
            <h2 class="philosophy-headline">
                reach your dreams<br>achieve your goals
            </h2>
            
            <p class="philosophy-subheading">
Oryphem Library mempersembahkan varian buku yang dilengkapi fitur pencatatan transaksi terintegrasi. Setiap kegiatan dicatat secara real-time dan terjamin keamanannya menggunakan teknologi Blockchain yang revolusioner, kami menggunakan Oryphem NFT untuk melakukan transaksi, memberikan pengalaman praktis tanpa risiko.
            </p>
            
<div class="philosophy-pillars">
    <div class="pillar">
        <div class="pillar-icon">🎯</div>
        <h3 class="pillar-title">Reach Your Dreams</h3>
        <p class="pillar-description">
Wujudkan potensi maksimal Anda! Oryphem Library hadir dengan varian buku panduan edukasi yang inovatif, didukung oleh fitur pencatatan transaksi yang sangat aman.
        </p>
    </div>

    <div class="pillar">
        <div class="pillar-icon">🏆</div>
        <h3 class="pillar-title">Achieve Your Goals</h3>
        <p class="pillar-description">
            Semua transaksi edukasi dicatat secara langsung menggunakan teknologi <b>Blockchain</b> untuk menjamin keamanan dan transparansi penuh.
        </p>
    </div>

    <div class="pillar">
        <div class="pillar-icon">🔒</div>
        <h3 class="pillar-title">Secure Transaction</h3>
        <p class="pillar-description">
            Untuk kegiatan transaksi dan pembelajaran, kami menggunakan <b>Sepolia Testnet Token</b> untuk deploy token, dan itu tercatat di etherscan sehingga bisa di audit, serta memberikan pengalaman praktis di lingkungan yang aman.
        </p>
    </div>
</div>
            
            <div class="philosophy-particles" id="particles">
                <!-- Particles will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <!-- Stats Section with Content -->
    <section class="stats-section" id="stats">
        <div class="section-header">
            <h2 class="section-title">Rekomendasi Buku</h2>
            <p class="section-subtitle">kami menyediakan beberapa referensi buku terbaik untuk dibaca</p>
        </div>
        <div class="philosophy-pillars">
                <div class="stat-card">
                    <div class="card-number">02</div>
                    <div class="card-image">
                        {{-- <img src="images/fitness-app.jpg" alt="Aplikasi Pelacak Kebugaran"> --}}
                    </div>
                    <h3 class="card-title">Aplikasi Pelacak Kebugaran Harian</h3>
                    <p class="card-description">Aplikasi mobile yang membantu pengguna memantau langkah, kalori, dan durasi olahraga mereka.</p>
                    <div class="card-tech">
                        <span class="tech-badge">Vue.js</span>
                        <span class="tech-badge">Firebase</span>
                        <span class="tech-badge">Tailwind CSS</span>
                        <span class="tech-badge">PWA</span>
                    </div>
                    <button class="card-cta" onclick="scrollToSection('about')">Explore</button>
                </div>
                <div class="stat-card">
                    <div class="card-number">02</div>
                    <div class="card-image">
                        {{-- <img src="images/fitness-app.jpg" alt="Aplikasi Pelacak Kebugaran"> --}}
                    </div>
                    <h3 class="card-title">Aplikasi Pelacak Kebugaran Harian</h3>
                    <p class="card-description">Aplikasi mobile yang membantu pengguna memantau langkah, kalori, dan durasi olahraga mereka.</p>
                    <div class="card-tech">
                        <span class="tech-badge">Vue.js</span>
                        <span class="tech-badge">Firebase</span>
                        <span class="tech-badge">Tailwind CSS</span>
                        <span class="tech-badge">PWA</span>
                    </div>
                    <button class="card-cta" onclick="scrollToSection('about')">Explore</button>
                </div>
        </div>
    </section>

    <!-- Footer -->
    <footer class="footer">
        <div class="footer-content">
            <div class="footer-brand">
                <div class="footer-logo">

                    <span class="logo-text">
                        <span class="prism">Oryphem</span>
                        <span class="flux">Library</span>
                    </span>
                </div>
                <p class="footer-description">
bersama Oryphem Library, kami menyediakan varian buku dengan pencatatan transaksi yang aman
                </p>
                <div class="footer-social">
                    <a href="#" class="social-icon">ig</a>
                    <a href="#" class="social-icon">in</a>
                </div>
            </div>
            
            <div class="footer-section">
                <h4>Services</h4>
                <div class="footer-links">
                    <a href="#">Web Development</a>
                    <a href="#">App Development</a>
                    <a href="#">Cloud Solutions</a>
                    <a href="#">AI Integration</a>
                </div>
            </div>
            
            <div class="footer-section">
                <h4>Company</h4>
                <div class="footer-links">
                    <a href="#">About Us</a>
                    <a href="#">Our Team</a>
                    <a href="#">Careers</a>
                    <a href="#">Press Kit</a>
                </div>
            </div>
            
            <div class="footer-section">
                <h4>Resources</h4>
                <div class="footer-links">
                    <a href="#">Documentation</a>
                    <a href="#">API Reference</a>
                    <a href="#">Blog</a>
                    <a href="#">Support</a>
                </div>
            </div>
        </div>
        
        <div class="footer-bottom">
            <div class="copyright">
                ©2025 Oryphem Tech. All rights reserved.
            </div>
            <div class="footer-credits">
                Developed by <a href="https://github.com/b4its" rel="nofollow" target="_blank">b4its</a>
            </div>
        </div>
    </footer>
<script src="{{  asset('assets/templatemo-prism-scripts.js') }}"></script>
<script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>

</body>
</html>